{
  "message" : "[0/1] Planning build\nBuilding for debugging...\n[0/2] Write swift-version-24593BA9C3E375BF.txt\nBuild complete! (0.12s)\nTest Suite 'All tests' started at 2025-01-08 18:59:34.900\nTest Suite 'debug.xctest' started at 2025-01-08 18:59:34.901\nTest Suite 'debug.xctest' passed at 2025-01-08 18:59:34.901\n\t Executed 0 tests, with 0 failures (0 unexpected) in 0.0 (0.0) seconds\nTest Suite 'All tests' passed at 2025-01-08 18:59:34.901\n\t Executed 0 tests, with 0 failures (0 unexpected) in 0.0 (0.0) seconds\n◇ Test run started.\n↳ Testing Library Version: 6.0.2 (cd448bbe5cc989d)\n◇ Test \"test No Exception\" started.\n◇ Test \"test Add\" started.\nSwift/IntegerTypes.swift:14377: Fatal error: Division by zero\n✔ Test \"test No Exception\" passed after 0.001 seconds.\n\n*** Signal 4: Backtracing from 0x7fd3c5b609e4... done ***\n\n*** Program crashed: Illegal instruction at 0x00007fd3c5b609e4 ***\n\nThread 0 \"SingleWithExcep\":\n\n0      0x00007fd3c4d845db <unknown> in libc.so.6\n1 [ra] 0x00007fd3c57370d8 _dispatch_sigsuspend + 23 in libdispatch.so\n2 [ra] 0x00007fd3c4d691d6 <unknown> in libc.so.6\n3 [ra] 0x00007fd3c4d6928b <unknown> in libc.so.6\n\nThread 1 crashed:\n\n 0                  0x00007fd3c5b609e4 closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 308 in libswiftCore.so\n 1 [ra]             0x00007fd3c5b60792 closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 257 in libswiftCore.so\n 2 [ra]             0x00007fd3c5b6064d closure #1 in _assertionFailure(_:_:file:line:flags:) + 380 in libswiftCore.so\n 3 [ra]             0x00007fd3c5ce3b46 _assertionFailure(_:_:file:line:flags:) + 229 in libswiftCore.so\n 4 [ra]             0x0000556c780a6851 div(_:_:) + 160 in SingleWithExceptionPackageTests.xctest at /solution/Sources/SingleWithException/SingleWithException.swift:2:12\n 5 [ra] [inlined]   0x0000556c780d309b freestanding macro expansion #1 of expect in module SingleWithExceptionTests file SingleWithExceptionTests.swift line 12 column 3 in SingleWithExceptionPackageTests.xctest at /tmp/swift-generated-sources/@__swiftmacro_24SingleWithExceptionTests0035SingleWithExceptionTestsswift_IgGGkfMX11_2_6expectfMf_.swift:1:26\n 6 [ra]             0x0000556c780d309b testAdd() + 122 in SingleWithExceptionPackageTests.xctest at /solution/Tests/SingleWithExceptionTests/SingleWithExceptionTests.swift:12:3\n 7 [ra]             0x0000556c780d278a closure #2 in $s24SingleWithExceptionTests7testAdd4TestfMp_13functestAdd__fMu_@Sendable () + 41 in SingleWithExceptionPackageTests.xctest at /tmp/swift-generated-sources/@__swiftmacro_24SingleWithExceptionTests7testAdd4TestfMp_.swift:6:20\n 8 [async]          0x00007fd3c620d270 __ifMainActorIsolationEnforced<A>(_:else:) in libTesting.so\n 9 [async]          0x0000556c780d2450 $s24SingleWithExceptionTests7testAdd4TestfMp_13functestAdd__fMu_@Sendable () in SingleWithExceptionPackageTests.xctest at /tmp/swift-generated-sources/@__swiftmacro_24SingleWithExceptionTests7testAdd4TestfMp_.swift:3\n10 [async]          0x00007fd3c61d50e0 closure #1 in closure #1 in Runner._runTestCase(_:within:) in libTesting.so\n11 [async] [thunk]  0x00007fd3c61deb80 partial apply for closure #1 in closure #1 in Runner._runTestCase(_:within:) in libTesting.so\n12 [async]          0x00007fd3c61997e0 specialized static Issue.withErrorRecording(at:configuration:isolation:_:) in libTesting.so\n13 [async]          0x00007fd3c61d4960 closure #1 in Runner._runTestCase(_:within:) in libTesting.so\n14 [async] [thunk]  0x00007fd3c61debc0 partial apply for closure #1 in Runner._runTestCase(_:within:) in libTesting.so\n15 [async]          0x00007fd3c61cd7a0 specialized static Test.Case.withCurrent<A>(_:perform:) in libTesting.so\n16 [async]          0x00007fd3c61d4490 Runner._runTestCase(_:within:) in libTesting.so\n17 [async]          0x00007fd3c61d4000 closure #2 in Runner._runTestCases<A>(_:within:) in libTesting.so\n18 [async] [thunk]  0x00007fd3c61deb70 partial apply for closure #2 in Runner._runTestCases<A>(_:within:) in libTesting.so\n19 [async]          0x00007fd3c61da300 specialized closure #1 in closure #1 in Runner._forEach<A, B>(in:for:_:) in libTestierror: Exited with unexpected signal code 4\nng.so\n20 [async] [thunk]  0x00007fd3c61deb60 partial apply for specialized closure #1 in closure #1 in Runner._forEach<A, B>(in:for:_:) in libTesting.so\n21 [async] [system] 0x00007fd3c59d4190 completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) in libswift_Concurrency.so\n\nThread 2:\n\n0      0x00007fd3c4e69042 <unknown> in libc.so.6\n1 [ra] 0x00007fd3c573e405 _dispatch_event_loop_drain + 52 in libdispatch.so\n\nThread 3:\n\n0      0x00007fd3c4e5b5ad <unknown> in libc.so.6\n1 [ra] 0x00007fd3c4dd2965 <unknown> in libc.so.6\n2 [ra] 0x00007fd3c4dd2bca <unknown> in libc.so.6\n3 [ra] 0x00007fd3c4dc52ec <unknown> in libc.so.6\n4 [ra] 0x00007fd3c614ea5f specialized String.withCString<A>(_:) + 142 in libTesting.so\n\nThread 4:\n\n0      0x00007fd3c4dd7d61 <unknown> in libc.so.6\n1 [ra] 0x00007fd3c4de3d83 <unknown> in libc.so.6\n\nThread 5:\n\n0      0x00007fd3c4dd7d61 <unknown> in libc.so.6\n1 [ra] 0x00007fd3c4de3d83 <unknown> in libc.so.6\n\nThread 6:\n\n0      0x00007fd3c4dd7d61 <unknown> in libc.so.6\n1 [ra] 0x00007fd3c4de3d83 <unknown> in libc.so.6\n\n\nRegisters:\n\nrax 0x0000000000000001  1\nrdx 0x0000000000000001  1\nrcx 0x0000000000000001  1\nrbx 0x00000007fd3bc009  34313322505\nrsi 0x0000000000000000  0\nrdi 0x00007fd3bc0094e0  00 00 00 00 00 00 00 00 35 00 00 00 00 00 00 00  ········5·······\nrbp 0x00007fd3c25d7850  90 78 5d c2 d3 7f 00 00 92 07 b6 c5 d3 7f 00 00  ·x]ÂÓ·····¶ÅÓ···\nrsp 0x00007fd3c25d7840  10 00 00 00 00 00 00 00 29 38 00 00 00 00 00 00  ········)8······\n r8 0x00007fd3bc0008e0  02 00 01 00 02 00 01 00 01 00 00 00 00 00 00 00  ················\n r9 0x0000000000000007  7\nr10 0x00007fd3bc0094f0  09 c0 3b fd 07 00 00 00 b6 82 99 19 39 ae 5b 7d  ·À;ý····¶···9®[}\nr11 0x7d5bae39199982b6  9033005037887521462\nr12 0x00007fd3c25d8688  00 00 00 00 00 00 00 00 30 ed 00 ac d3 7f 00 00  ········0í·¬Ó···\nr13 0x0000000000000000  0\nr14 0x0000000000000001  1\nr15 0x0000000000000001  1\nrip 0x00007fd3c5b609e4  0f 0b 48 83 ec 08 48 8d 05 0f cd 46 00 48 8d 3d  ··H·ì·H···ÍF·H·=\n\nrflags 0x0000000000010202  \n\ncs 0x0033  fs 0x0000  gs 0x0000\n\n\nImages (16 omitted):\n\n0x0000556c7809e000–0x0000556c78115dc8 <no build ID>                            SingleWithExceptionPackageTests.xctest /solution/.build/x86_64-unknown-linux-gnu/debug/SingleWithExceptionPackageTests.xctest\n0x00007fd3c4d3f000–0x00007fd3c4eeec8d 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6 libc.so.6                              /usr/lib/x86_64-linux-gnu/libc.so.6\n0x00007fd3c5701000–0x00007fd3c573f9c1 <no build ID>                            libdispatch.so                         /usr/lib/swift/linux/libdispatch.so\n0x00007fd3c5968000–0x00007fd3c59edfc0 2abcae414e1196cafa29e10b5161ebbb05add43b libswift_Concurrency.so                /usr/lib/swift/linux/libswift_Concurrency.so\n0x00007fd3c5a01000–0x00007fd3c5f95ed0 2c7478c6e1a4d502046f5650534759839f0eb256 libswiftCore.so                        /usr/lib/swift/linux/libswiftCore.so\n0x00007fd3c610c000–0x00007fd3c62460d8 <no build ID>                            libTesting.so                          /usr/lib/swift/linux/libTesting.so\n\nBacktrace took 0.02s\n\n",
  "status" : "error",
  "tests" : [

  ],
  "version" : 3
}