{
  "message" : "[0/1] Planning build\nBuilding for debugging...\n[0/2] Write swift-version-24593BA9C3E375BF.txt\nBuild complete! (0.20s)\nTest Suite 'All tests' started at 2025-03-30 12:58:20.571\nTest Suite 'debug.xctest' started at 2025-03-30 12:58:20.572\nTest Suite 'debug.xctest' passed at 2025-03-30 12:58:20.572\n\t Executed 0 tests, with 0 failures (0 unexpected) in 0.0 (0.0) seconds\nTest Suite 'All tests' passed at 2025-03-30 12:58:20.572\n\t Executed 0 tests, with 0 failures (0 unexpected) in 0.0 (0.0) seconds\n◇ Test run started.\n↳ Testing Library Version: 6.1 (43b6f88e2f2712e)\n↳ Target Platform: x86_64-unknown-linux-gnu\n◇ Test \"test No Exception\" started.\n◇ Test \"test Add\" started.\nSwift/IntegerTypes.swift:9012: Fatal error: Division by zero\n\n*** Signal 4: Backtracing from 0x736ebb3b5015... done ***\n\n*** Program crashed: Illegal instruction at 0x0000736ebb3b5015 ***\n\nThread 0 \"SingleWithExcep\":\n\n0  0x0000736eb9b8a48a <unknown> in libc-2.31.so\n\nThread 1:\n\n0      0x0000736ebb6d2caa swift_conformsToProtocolMaybeInstantiateSuperclasses(swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolDescriptor<swift::InProcess> const*, bool) + 1434 in libswiftCore.so\n1 [ra] 0x0000736ebb6d1e74 swift_conformsToProtocolCommon + 19 in libswiftCore.so\n2 [ra] 0x0000736ebb67ad98 swift::_conformsToProtocol(swift::OpaqueValue const*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolDescriptorRef<swift::InProcess>, swift::TargetWitnessTable<swift::InProcess> const**) + 23 in libswiftCore.so\n3 [ra] 0x0000736ebb6804f3 tryCastToConstrainedOpaqueExistential(swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetMetadata<swift::InProcess> const*&, swift::TargetMetadata<swift::InProcess> const*&, bool, bool) + 178 in libswiftCore.so\n4 [ra] 0x0000736ebb67ec59 tryCast(swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetMetadata<swift::InProcess> const*&, swift::TargetMetadata<swift::InProcess> const*&, bool, bool) + 600 in libswiftCore.so\n5 [ra] 0x0000736ebb67e998 swift_dynamicCast + 71 in libswiftCore.so\n6 [ra] 0x0000736ebb612e7c __VaListBuilder.append(_:) + 107 in libswiftCore.so\n\nThread 2:\n\n0  0x0000736eb9c6668e <unknown> in libc-2.31.so\n\nThread 3 crashed:\n\n 0                  0x0000736ebb3b5015 closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 309 in libswiftCore.so\n 1 [ra]             0x0000736ebb3b4e05 closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 324 in libswiftCore.so\n 2 [ra]             0x0000736ebb3b4c7c closure #1 in _assertionFailure(_:_:file:line:flags:) + 379 in libswiftCore.so\n 3 [ra]             0x0000736ebb52ac25 _assertionFailure(_:_:file:line:flags:) + 276 in libswiftCore.so\n 4 [ra]             0x00006411cafd57c1 div(_:_:) + 160 in SingleWithExceptionPackageTests.xctest at /solution/Sources/SingleWithException/SingleWithException.swift:2:12\n 5 [ra] [inlined]   0x00006411cafe7a2b freestanding macro expansion #1 of expect in module SingleWithExceptionTests file SingleWithExceptionTests.swift line 12 column 3 in SingleWithExceptionPackageTests.xctest at /tmp/swift-generated-sources/@__swiftmacro_24SingleWithExceptionTests0035SingleWithExceptionTestsswift_IgGGkfMX11_2_6expectfMf_.swift:1:26\n 6 [ra]             0x00006411cafe7a2b testAdd() + 122 in SingleWithExceptionPackageTests.xctest at /solution/Tests/SingleWithExceptionTests/SingleWithExceptionTests.swift:12:3\n 7 [ra]             0x00006411cafd50f1 $s24SingleWithExceptionTests7testAdd4TestfMp_7__localfMu_ #1 @Sendable (_:) in $s24SingleWithExceptionTests7testAdd4TestfMp_8dc684a58fMu_@Sendable () + 32 in SingleWithExceptionPackageTests.xctest at /tmp/swift-generated-sources/@__swiftmacro_24SingleWithExceptionTests7testAdd4TestfMp_.swift:4:67\n 8 [async]          0x00006411cafd4f00 $s24SingleWithExceptionTests7testAdd4TestfMp_8dc684a58fMu_@Sendable () in SingleWithExceptionPackageTests.xctest at /tmp/swift-generated-sources/@__swiftmacro_24SingleWithExceptionTests7testAdd4TestfMp_.swift:6\n 9 [async]          0x0000736eb9fd7310 specialized Runner._applyScopingTraits(for:testCase:_:) in libTesting.so\n10 [async]          0x0000736eb9fd3920 closure #1 in closure #1 in closure #1 in Runner._runTestCase(_:within:) in libTesting.so\n11 [async] [thunk]  0x0000736eb9fdc460 partial apply for closure #1 in closure #1 in closure #1 in Runner._runTestCase(_:within:) in libTesting.so\n12 [async]          0x0000736eba015990 withTimeLimit(for:configuration:_:timeoutHandler:) in libTesting.so\n13 [async]          0x0000736eb9fd36d0 closure #1 in closure #1 in Runner._runTestCase(_:within:) in libTesting.so\n14 [async] [thunk]  0x0000736eb9fdc450 partial apply for closure #1 in closure #1 in Runner._runTestCase(_:within:) in libTesting.so\n15 [async]          0x0000736eb9fa0410 static Issue.withErrorRecording(at:configuration:isolation:_:) in libTesting.so\n16 [async]          0x0000736eb9fd3420 closure #1 in Runner._runTestCase(_:within:) in libTesting.so\n17 [async] [thunk]  0x0000736eb9fdc4c0 partial apply for closure #1 in Runner._runTestCase(_:within:) in libTesting.so\n18 [async]          0x0000736ebb15c130 TaskLocal.withValueImpl<A>(_:operation:isolation:file:line:) in libswift_Concurrency.so\n19 [async]          0x0000736ebb15c000 TaskLocal.withValue<A>(_:operation:isolation:file:line:) in libswift_Concurrency.so\n20 [async]          0x0000736eb9fca510 static Test.Case.withCurrent<A>(_:perform:) in libTesting.so\n21 [async]          0x0000736eb9fd30a0 Runner._runTestCase(_:within:) in libTesting.so\n22 [async]          0x0000736eb9fd2d80 closure #2 in Runner._runTestCases<A>(_:within:) in libTesting.so\n23 [async] [thunk]  0x0000736eb9fdc440 partial apply for closure #2 in Runner._runTestCases<A>(_:within:) in libTesting.so\n24 [async]          0x0000736eb9fd6a60 specialized closure #1 in closure #1 in Runner._forEach<A, B>(in:for:_:) in libTesting.so\n25 [async] [thunk]  0x0000736eb9fdc430 partial apply for specialized closure #1 in closure #1 in Runner._forEach<A, B>(in:for:_:) in libTesting.so\n26 [async] [system] 0x0000736ebb189ce0 completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) in libswift_Concurrency.so\n\nThread 4:\n\n0  0x0000736eb9d58678 do_futex_wait.constprop.0 + 72 in libpthread-2.31.so\n\n\nRegisters:\n\nrax 0x0000000000000000  0\nrdx 0x0000000000000001  1\nrcx 0x0000000000000001  1\nrbx 0x0000000000000000  0\nrsi 0x0000736ea40008d2  01 00 04 00 01 00 06 00 03 00 01 00 07 00 00 00  ················\nrdi 0x0000736ea4009570  00 00 00 00 00 00 00 00 d0 08 00 a4 6e 73 00 00  ········Ð··¤ns··\nrbp 0x0000736eb5fff8a0  e0 f8 ff b5 6e 73 00 00 05 4e 3b bb 6e 73 00 00  àøÿµns···N;»ns··\nrsp 0x0000736eb5fff890  10 00 00 00 00 00 00 00 34 23 00 00 00 00 00 00  ········4#······\n r8 0x0000000000000000  0\n r9 0x0000736eb5fff680  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················\nr10 0x0000736ebb769cf7  00 6f 66 66 73 65 74 00 22 2c 20 69 6e 74 56 61  ·offset·\", intVa\nr11 0x00006411cb02e3d0  44 69 76 69 73 69 6f 6e 20 62 79 20 7a 65 72 6f  Division by zero\nr12 0x0000736eb60006c8  00 00 00 00 00 00 00 00 60 9a 01 a4 6e 73 00 00  ········`··¤ns··\nr13 0x0000736ea4019a60  28 65 19 bb 6e 73 00 00 03 00 00 00 00 00 00 00  (e·»ns··········\nr14 0x0000000000000001  1\nr15 0x000000000000000b  11\nrip 0x0000736ebb3b5015  0f 0b 48 83 ec 08 48 8d 05 ae cb 3b 00 48 8d 3d  ··H·ì·H··®Ë;·H·=\n\nrflags 0x0000000000010206  PF\n\ncs 0x0033  fs 0x0000  gs 0x0000\n\n\nImages (20 omitted):\n\n0x00006411cafb3000–0x00006411cb02ae88 e94fcb384c607c8bd807e4c757fe51f3521be4cf SingleWithExceptionPackageTests.xctest /solution/.build/x86_64-unknown-linux-gnu/debug/SingleWithExceptionPackageTests.xctest\n0x0000736eb9b47000–0x0000736eb9ce0864 0323ab4806bee6f846d9ad4bccfc29afdca49a58 libc-2.31.so                           /usr/lib/x86_64-linux-gnu/libc-2.31.so\n0x0000736eb9d46000–0x0000736eb9d5c545 5cfb896dd40f90aa8c6c8bb856004d1f5cfe293c libpthread-2.31.so               error: Exited with unexpected signal code 4\n      /usr/lib/x86_64-linux-gnu/libpthread-2.31.so\n0x0000736eb9f13000–0x0000736eba063098 799bfe278acd1dfc119a63de59c4a0dc87e237b1 libTesting.so                          /usr/lib/swift/linux/libTesting.so\n0x0000736ebb10b000–0x0000736ebb190ed0 a6a1b42dd9206cbc2f35189de126829d74ce9807 libswift_Concurrency.so                /usr/lib/swift/linux/libswift_Concurrency.so\n0x0000736ebb1a3000–0x0000736ebb733a70 967daf3eb33c731c8e19e67d922a14322d5fe7d6 libswiftCore.so                        /usr/lib/swift/linux/libswiftCore.so\n\nBacktrace took 0.04s\n\n",
  "status" : "error",
  "tests" : [

  ],
  "version" : 3
}